# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image_tag: experiment

replicas:
  backend_umbrella: 3
  graphql-gateway: 1
  web: 1

domain: opmar.local

redis:
  auth:
    existingSecret: "opmar"
    existingSecretPasswordKey: "redis-password"
  image:
    repository: redis
    tag: latest
    pullPolicy: Always
