# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image_tag: experiment-448911025f5c7085ee14ec3b7eb720fe0b508d3c

replicas:
  backend_umbrella: 1
  web: 1

domain: opmar.local
