# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image_tag: experiment-bf4c64b7a437f76d6fc9158226e38056a98b486c

replicas:
  backend_umbrella: 1
  web: 1

secret_names:
  # must defined
  # secret-key-base
  backend_umbrella: backend-umbrella

domain: opmar.local
