# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image_tag: experiment-4437a47b552bce37a66d998eb67b378cb8220783

replicas:
  backend_umbrella: 3
  web: 1

domain: opmar.local

redis:
  auth:
    existingSecret: "opmar"
    existingSecretPasswordKey: "redis-password"