# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image_tag: experiment

replicas:
  backend_umbrella: 1
  web: 1

secret_names:
  # must defined
  # secret-key-base
  backend_umbrella: backend-umbrella

domains:
  backend_umbrella: umbrella.op.local
  web: op.local
