apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-umbrella
  labels:
    app: backend-umbrella
spec:
  replicas: {{ .Values.replicas.backend_umbrella }}
  selector:
    matchLabels:
      app: backend-umbrella
  template:
    metadata:
      labels:
        app: backend-umbrella
    spec:
      containers:
        - name: backend-umbrella
          image: ghcr.io/ndthanhdev/open_marketplace_backend_umbrella:{{ .Values.image_tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: opmar
                  key: secret-key-base
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opmar
                  key: redis-password
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis-master
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-umbrella
spec:
  selector:
    app: backend-umbrella
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
