apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  labels:
    app: graphql-gateway
spec:
  replicas: {{ .Values.replicas.graphql-gateway }}
  selector:
    matchLabels:
      app: graphql-gateway
  template:
    metadata:
      labels:
        app: graphql-gateway
    spec:
      containers:
        - name: graphql-gateway
          image: ghcr.io/ndthanhdev/open_marketplace_graphql-gateway:{{ .Values.image_tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
spec:
  selector:
    app: graphql-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
