apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: backend-umbrella
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web
              port:
                number: 80