{{- if (include "opmar.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: opmar
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secret-key-base: {{ include "opmar.secretKeyBase" . }}
{{- end -}}
