{{- if (include "opmar.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opmar.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secret-key-base: {{ include "opmar.secretKeyBase" . }}
  redis-password: {{ include "opmar.redisPassword" . }}
{{- end -}}
