services:
  backend:
    build:
      context: C:\Users\ndtha\sources\backend
      dockerfile: C:\Users\ndtha\sources\backend\Dockerfile
    depends_on:
      db:
        condition: service_started
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: open_marketplace
    networks:
      default: null
    ports:
    - mode: ingress
      target: 4000
      published: 4000
      protocol: tcp
  db:
    build:
      context: C:\Users\ndtha\sources\db
      dockerfile: C:\Users\ndtha\sources\db\Dockerfile
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: open_marketplace
    networks:
      default: null
    ports:
    - mode: ingress
      target: 5432
      published: 5432
      protocol: tcp
networks:
  default:
    name: open_marketplace_default
