version: "3.x"
services:
  backend:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "4000:4000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
