version: "3.x"
services:
  backend:
    build:
      context: .
      ports:
      - "4000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432"
