version: "3.x"
services:
  backend:
    build:
      context: .
    expose:
      - "4000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    expose:
      - "5432"
ports:
  - "5432"
  - "4000"
