version: "3.x"
services:
  backend:
    image: elixir:alpine
    expose:
      - "4000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    expose:
      - "5432"
