name: Deploy

on:
  workflow_dispatch:
    inputs:
      chart:
        required: true
        description: The git ref of the chart to deploy
        default: master
      image:
        description: "Image to deploy"
        required: true
        default: experiment
      namespace:
        description: "Namespace to deploy"
        required: true
        default: experiment
      domain:
        description: "Domain to deploy"
        required: true
        default: opmar.duckdn.org

env:
  REGISTRY: ghcr.io

jobs:
  deploy-to-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.chartRef }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Repository Meta"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy experiment
        uses: deliverybot/helm@v1
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBE_CONFIG_EXPERIMENT }}
        with:
          helm: helm3
          namespace: ${{ github.event.inputs.namespace }}
          release: op
          chart: chart/
          token: ${{ secrets.GITHUB_TOKEN }}
          values: |
            image_tag: ${{ github.event.inputs.image }}
            domain: ${{ github.event.inputs.domain }}
