on:
  workflow_dispatch:
    inputs:
      name:
        description: name of the build
        required: false
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compose up
        run: "docker-compose -f .docker/docker-compose.yaml --project-directory ./ up -d"
      - name: Test
        run: "docker-compose -f .docker/docker-compose.yaml --project-directory ./ exec -T backend mix test"